### ISSUE TITLE
Error when running openstack-ansible setup-hosts.yml

### ISSUE THREAD

**Issue by rahulunair** [UTSA-OCI/OCI-OpenStack-Ansible#6]
Getting "connection reset by peer" error when running the command, 

```
openstack-ansible setup-hosts.yml
```

possible fix , edit ansible.cfg and add line 

```
scp_if_ssh=True
```

at the end of ssh config block, please see: http://docs.ansible.com/ansible/intro_configuration.html#scp-if-ssh

![image 1](https://cloud.githubusercontent.com/assets/786476/10921655/60d4282a-823c-11e5-8454-a4271ee1a24c.png)

**Comment by mmuppidi** [comment]
The error is because the sftp subsystem is disabled in your sshd_config of the remote hosts. Simple solution would be adding `scp_if_ssh=True` in `ansible.cfg` file. In the ansible.cfg file look for the following section and add the line as shown below

```
[ssh_connection]
pipelining = True
ssh_args = -o ControlMaster=auto -o ControlPersist=60s -o TCPKeepAlive=yes -o ServerAliveInterval=5 -o ServerAliveCountMax=3
```

Add `scp_if_ssh=True` after this section as shown below

```
[ssh_connection]
pipelining = True
ssh_args = -o ControlMaster=auto -o ControlPersist=60s -o TCPKeepAlive=yes -o ServerAliveInterval=5 -o ServerAliveCountMax=3
scp_if_ssh=True
```

This should fix the issue. 

Closing the issue.
